name: e_commerce_app_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

#--------------------PACKAGES--------------------#
dependencies:
  flutter:
    sdk: flutter



  # Utility Packages
  http: ^1.1.0
  logger: ^2.0.1
  flutter_native_splash: ^2.4.2
  intl: ^0.20.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.0
  url_launcher: ^6.2.6
  flutter_dropzone: ^4.2.0
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^6.0.3
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0


  # Web Specific
  web: ^0.5.1
  html: ^0.15.4
  fl_chart: ^0.69.0
  data_table_2: ^2.5.12
  url_strategy: ^0.3.0
  universal_html: ^2.2.4

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get_storage: ^2.1.1
  get: ^4.6.5

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3



  # Product Specific

#---------------./ PACKAGES END---------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------LOCAL ASSETS-----------------#
  assets:
    - assets/logos/
    - assets/images/user/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/products/

  #-----------------LOCAL FONTS-----------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic

